apiVersion: openedge.dev/v1
kind: Org
metadata:
  name: u_user_3HsJVZ8ADRO61vdZNrzI0nDVBCS
  slug: u_user_3HsJVZ8ADRO61vdZNrzI0nDVBCS
  plan: pro
  generatedAt: "2026-08-14T08:29:10.366Z"
  managedBy: OpenEdge GitOps
projects:
  - name: i-want-to-build-my-first-project-on-shadw-cloud--i-am-not-a-developer--create-the-simplest-useful-web-application-possible--give-me-every-file-i-need--explain-how-to-put-it-in-github--and-walk-me-through-deploying-it-to-shadw-cloud-one-step-at-a-time--do-not-assume-i-know-git--node-js--or-cloud-deployment-i-want-to-build-a-museum-crowd-info-app-
    framework: auto
    build:
      installCommand: ""
      buildCommand: ""
      outputDirectory: ""
    functions:
      runtime: fluid
      maxDuration: 300
      memory: 2048
      regions:
        - san-jose
      failover: false
databases: []
