apiVersion: openedge.dev/v1
kind: Meta
org: u_user_3HsJVZ8ADRO61vdZNrzI0nDVBCS
name: u_user_3HsJVZ8ADRO61vdZNrzI0nDVBCS
plan: pro
region: virginia
projectCount: 2
generatedAt: "2026-08-14T08:29:59.382Z"
managedBy: OpenEdge GitOps
